last_update = 1672233230373
api_url = "https://api.playit.cloud/agent"
ping_target_addresses = ["23.133.216.1:5530", "ping.playit.gg"]
control_address = "control.ply.gg"
refresh_from_api = true
api_refresh_rate = 5000
ping_interval = 5000
secret_key = "13a50d4f4a8eee078ac26a5a8fbf1275253a650f07bac66f5b463329ff50b4fa"

[[mappings]]
proto = "udp"
tunnel_ip = "147.185.221.194"
tunnel_from_port = 56214
local_port = 24454

[[mappings]]
proto = "tcp"
tunnel_ip = "147.185.221.180"
tunnel_from_port = 20974
local_port = 25565
